# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatsPLAN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatsPLAN
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  

  pod "FloatingLabelTextFieldSwiftUI"

  pod "ValidatedPropertyKit"

  pod "FloatingButton"

  pod 'MaterialComponents/Snackbar'    
end
